version: '3.9'

name: blog

services:
  cache:
    image: redis:latest
    ports:
      - 6379:6379
    restart: always
    command: redis-server --requirepass 

  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=blog
    volumes:
      - db_data:/var/lib/mysql
      
  api:
    image: q1anxi/blog_api:latest
    ports:
      - 8080:8080
    restart: always
  
  web:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./ssl:/etc/nginx/ssl
      - ./default.conf:/etc/nginx/nginx.conf
      - ./dist:/usr/share/qianxi.me
    restart: always

volumes:
  db_data:
