// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./views/404.vue')['default']
    Banner: typeof import('./components/banner/index.vue')['default']
    Blossom: typeof import('./components/blossom/index.vue')['default']
    Footer: typeof import('./components/footer/index.vue')['default']
    Index: typeof import('./views/Index.vue')['default']
    Posts: typeof import('./views/Posts.vue')['default']
    Profile: typeof import('./components/profile/index.vue')['default']
  }
}

export { }
