// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    404: typeof import('./views/404.vue')['default']
    Article: typeof import('./components/article/index.vue')['default']
    Banner: typeof import('./components/banner/index.vue')['default']
    Blog: typeof import('./views/Blog.vue')['default']
    Blossom: typeof import('./components/blossom/index.vue')['default']
    Footer: typeof import('./components/footer/index.vue')['default']
    Index: typeof import('./views/Index.vue')['default']
    Item: typeof import('./components/posts/item.vue')['default']
    Markdown: typeof import('./components/article/markdown.vue')['default']
    Post: typeof import('./views/Post.vue')['default']
    Posts: typeof import('./components/posts/index.vue')['default']
    Profile: typeof import('./components/profile/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
