name: cd

on:
  push:
    branches: [ master ]
    paths:
      - "src/**"  
      - "locales/*"
      - "index.html"
      - "public/*"
  pull_request:
    branches: [ master ]
    paths:
      - "src/**"  
      - "locales/*"
      - "index.html"
      - "public/*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['17.x']

    steps:
    - uses: actions/checkout@v2

    - uses: pnpm/action-setup@v2.1.0
      with:
        version: latest
        run_install: |
          - recursive: true
            args: [--frozen-lockfile, --strict-peer-dependencies]
          - args: [--global, gulp, prettier, typescript]

    - name: build 
      run: pnpm run build

    - name: upload file
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "dist"
        target: "/root/qianxi.me/"