name: Create a new post

on:
  issues:
    types:
      - "opened"
    labels:
      - "post"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Download dep
        run: go mod download

      - name: Create a new post
        run: go run . -op=create
        env:
          USER_NAME: ${{secrets.USER_NAME}}
          PASSWORD: ${{secrets.PASSWORD}}
