name: Go

on:
  push:
    branches: [ master ]
    paths:
      - "api"
      - "cms"
  pull_request:
    branches: [ master ]
    paths:
      - "api"
      - "cms"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Fmt api
      run: cd api && go fmt ./...

    - name: Fmt cms
      run: cd cms && go fmt ./...