name: Update a post

on:
  issues:
    types:
      - "edited"
    labels: 
      - "post"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Download dep
      run: cd cms && go mod download

    - name: Update a post
      run: cd cmd && go run . -op=update
      env: 
        USER_NAME: ${{secrets.USER_NAME}}
        PASSWORD: ${{secrets.PASSWORD}}